name: planner
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  splashscreen: ^1.3.5
  sqflite: ^2.4.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.1.2
  bottom_picker: ^2.8.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700